ActiveDirectory::ATTRIBUTE_DEFINITIONS = [
  # Top
  { :name => "dn",                  :ldap_name => "distinguishedname",    :attribute_type => "string" },
  { :name => "name",                :ldap_name => "name",                 :attribute_type => "string" },
  { :name => "system_flags",        :ldap_name => "systemflags",          :attribute_type => "flags" },
  { :name => "display_name",        :ldap_name => "displayname",          :attribute_type => "string" },
  { :name => "description",         :ldap_name => "description",          :attribute_type => "string" },
  { :name => "proxy_addresses",     :ldap_name => "proxyaddresses",       :attribute_type => "array" },
  { :name => "when_created",        :ldap_name => "whencreated",          :attribute_type => "generalized_time" },
  { :name => "when_changed",        :ldap_name => "whenchanged",          :attribute_type => "generalized_time" },
  { :name => "admin_display_name",  :ldap_name => "admindisplayname",     :attribute_type => "string" },
  { :name => "admin_description",   :ldap_name => "admindescription",     :attribute_type => "string" },
  { :name => "unix_member_of",      :ldap_name => "mssfu30posixmemberof", :attribute_type => "array" },

  # Person
  { :name => "last_name", :ldap_name => "sn", :attribute_type => "string" },
  { :name => "phone_number", :ldap_name => "telephonenumber", :attribute_type => "string" },
  { :name => "password", :ldap_name => "userpassword", :attribute_type => "string" },

  # Organizational Person
  { :name => "address", :ldap_name => "streetaddress", :attribute_type => "string" },
  { :name => "home_address", :ldap_name => "homepostaladdress", :attribute_type => "string" },
  { :name => "assistant_dn", :ldap_name => "assistant", :attribute_type => "dn" },
  { :name => "company_name", :ldap_name => "company", :attribute_type => "string" },
  { :name => "country_code", :ldap_name => "countrycode", :attribute_type => "integer" },
  { :name => "country_name", :ldap_name => "c", :attribute_type => "string" },
  { :name => "department", :ldap_name => "department", :attribute_type => "string" },
  { :name => "division", :ldap_name => "division", :attribute_type => "string" },
  { :name => "email", :ldap_name => "mail", :attribute_type => "string" },
  { :name => "employee_id", :ldap_name => "employeeid", :attribute_type => "string" },
  { :name => "fax_number", :ldap_name => "facsimiletelephonenumber", :attribute_type => "string" },
  { :name => "generation_qualifier", :ldap_name => "generationqualifier", :attribute_type => "string" },
  { :name => "first_name", :ldap_name => "givenname", :attribute_type => "string" },
  { :name => "initials", :ldap_name => "initials", :attribute_type => "string" },
  { :name => "locality_name", :ldap_name => "l", :attribute_type => "string" },
  { :name => "manager_dn", :ldap_name => "manager", :attribute_type => "dn" },
  { :name => "organizational_unit", :ldap_name => "ou", :attribute_type => "string" },
  { :name => "other_mailbox", :ldap_name => "othermailbox", :attribute_type => "string" },
  { :name => "middle_name", :ldap_name => "middlename", :attribute_type => "string" },

  # User
  { :name => "account_expires", :ldap_name => "accountexpires", :attribute_type => "timestamp" },
  { :name => "admin_count", :ldap_name => "admincount", :attribute_type => "integer" },
  { :name => "last_bad_password_at", :ldap_name => "badpasswordtime", :attribute_type => "timestamp" },
  { :name => "bad_password_count", :ldap_name => "badpwdcount", :attribute_type => "integer" },
  { :name => "home_directory", :ldap_name => "homedirectory", :attribute_type => "string" },
  { :name => "home_drive", :ldap_name => "homedrive", :attribute_type => "string" },
  { :name => "last_logged_in_at", :ldap_name => "lastlogon", :attribute_type => "timestamp" },
  { :name => "locked_out_at", :ldap_name => "lockouttime", :attribute_type => "timestamp" },
  { :name => "logged_in_count", :ldap_name => "logoncount", :attribute_type => "integer" },
  { :name => "primary_group_id", :ldap_name => "primarygroupid", :attribute_type => "integer" },
  { :name => "profile_path", :ldap_name => "profilepath", :attribute_type => "string" },
  { :name => "password_last_set_at", :ldap_name => "pwdlastset", :attribute_type => "timestamp" },
  { :name => "script_path", :ldap_name => "scriptpath", :attribute_type => "string" },
  { :name => "service_principal_names", :ldap_name => "serviceprincipalname", :attribute_type => "array" },
  { :name => "unicode_password", :ldap_name => "unicodepwd", :attribute_type => "unicode_password" },
  { :name => "account_control", :ldap_name => "useraccountcontrol", :attribute_type => "user_account_control" },
  { :name => "parameters", :ldap_name =>  "userparameters", :attribute_type => "string" },
  { :name => "principal_name", :ldap_name => "userprincipalname", :attribute_type => "string" },
  { :name => "uid", :ldap_name => "uid", :attribute_type => "string" },

  # Security Descriptor
  { :name => "sam_account_name", :ldap_name => "samaccountname", :attribute_type => "string" },
]