AD::Framework.register_attributes([
  # Top
  { :name => "name",                :ldap_name => "name",                 :type => "string" },
  { :name => "system_flags",        :ldap_name => "systemflags",          :type => "flags" },
  { :name => "display_name",        :ldap_name => "displayname",          :type => "string" },
  { :name => "description",         :ldap_name => "description",          :type => "string" },
  { :name => "proxy_addresses",     :ldap_name => "proxyaddresses",       :type => "array" },
  { :name => "when_created",        :ldap_name => "whencreated",          :type => "generalized_time" },
  { :name => "when_changed",        :ldap_name => "whenchanged",          :type => "generalized_time" },
  { :name => "admin_display_name",  :ldap_name => "admindisplayname",     :type => "string" },
  { :name => "admin_description",   :ldap_name => "admindescription",     :type => "string" },
  { :name => "unix_member_of",      :ldap_name => "mssfu30posixmemberof", :type => "array" },

  # Person
  { :name => "last_name", :ldap_name => "sn", :type => "string" },
  { :name => "phone_number", :ldap_name => "telephonenumber", :type => "string" },
  { :name => "password", :ldap_name => "userpassword", :type => "string" },

  # Organizational Person
  { :name => "address", :ldap_name => "streetaddress", :type => "string" },
  { :name => "home_address", :ldap_name => "homepostaladdress", :type => "string" },
  { :name => "assistant_dn", :ldap_name => "assistant", :type => "dn" },
  { :name => "company_name", :ldap_name => "company", :type => "string" },
  { :name => "country_code", :ldap_name => "countrycode", :type => "integer" },
  { :name => "country_name", :ldap_name => "c", :type => "string" },
  { :name => "department", :ldap_name => "department", :type => "string" },
  { :name => "division", :ldap_name => "division", :type => "string" },
  { :name => "email", :ldap_name => "mail", :type => "string" },
  { :name => "employee_id", :ldap_name => "employeeid", :type => "string" },
  { :name => "fax_number", :ldap_name => "facsimiletelephonenumber", :type => "string" },
  { :name => "generation_qualifier", :ldap_name => "generationqualifier", :type => "string" },
  { :name => "first_name", :ldap_name => "givenname", :type => "string" },
  { :name => "initials", :ldap_name => "initials", :type => "string" },
  { :name => "locality_name", :ldap_name => "l", :type => "string" },
  { :name => "manager_dn", :ldap_name => "manager", :type => "dn" },
  { :name => "organizational_unit", :ldap_name => "ou", :type => "string" },
  { :name => "other_mailbox", :ldap_name => "othermailbox", :type => "string" },
  { :name => "middle_name", :ldap_name => "middlename", :type => "string" },

  # User
  { :name => "account_expires", :ldap_name => "accountexpires", :type => "timestamp" },
  { :name => "admin_count", :ldap_name => "admincount", :type => "integer" },
  { :name => "last_bad_password_at", :ldap_name => "badpasswordtime", :type => "timestamp" },
  { :name => "bad_password_count", :ldap_name => "badpwdcount", :type => "integer" },
  { :name => "home_directory", :ldap_name => "homedirectory", :type => "string" },
  { :name => "home_drive", :ldap_name => "homedrive", :type => "string" },
  { :name => "last_logged_in_at", :ldap_name => "lastlogon", :type => "timestamp" },
  { :name => "locked_out_at", :ldap_name => "lockouttime", :type => "timestamp" },
  { :name => "logged_in_count", :ldap_name => "logoncount", :type => "integer" },
  { :name => "primary_group_id", :ldap_name => "primarygroupid", :type => "integer" },
  { :name => "profile_path", :ldap_name => "profilepath", :type => "string" },
  { :name => "password_last_set_at", :ldap_name => "pwdlastset", :type => "timestamp" },
  { :name => "script_path", :ldap_name => "scriptpath", :type => "string" },
  { :name => "service_principal_names", :ldap_name => "serviceprincipalname", :type => "array" },
  { :name => "unicode_password", :ldap_name => "unicodepwd", :type => "unicode_password" },
  { :name => "account_control", :ldap_name => "useraccountcontrol", :type => "flags" },
  { :name => "parameters", :ldap_name =>  "userparameters", :type => "string" },
  { :name => "principal_name", :ldap_name => "userprincipalname", :type => "string" },
  { :name => "uid", :ldap_name => "uid", :type => "string" },

  # Security Descriptor
  { :name => "sam_account_name", :ldap_name => "samaccountname", :type => "string" },
])