AD::Framework.register_attributes([
  { :name => "address",             :ldap_name => "streetaddress",            :type => "string" },
  { :name => "home_address",        :ldap_name => "homepostaladdress",        :type => "string" },
  { :name => "assistant_dn",        :ldap_name => "assistant",                :type => "dn" },
  { :name => "company_name",        :ldap_name => "company",                  :type => "string" },
  { :name => "country_code",        :ldap_name => "countrycode",              :type => "integer" },
  { :name => "country_name",        :ldap_name => "c",                        :type => "string" },
  { :name => "department",          :ldap_name => "department",               :type => "string" },
  { :name => "division",            :ldap_name => "division",                 :type => "string" },
  { :name => "email",               :ldap_name => "mail",                     :type => "string" },
  { :name => "employee_id",         :ldap_name => "employeeid",               :type => "string" },
  { :name => "fax_number",          :ldap_name => "facsimiletelephonenumber", :type => "string" },
  { :name => "generation",          :ldap_name => "generationqualifier",      :type => "string" },
  { :name => "first_name",          :ldap_name => "givenname",                :type => "string" },
  { :name => "initials",            :ldap_name => "initials",                 :type => "string" },
  { :name => "locality_name",       :ldap_name => "l",                        :type => "string" },
  { :name => "manager_dn",          :ldap_name => "manager",                  :type => "dn" },
  { :name => "organizational_unit", :ldap_name => "ou",                       :type => "string" },
  { :name => "other_mailbox",       :ldap_name => "othermailbox",             :type => "string" },
  { :name => "middle_name",         :ldap_name => "middlename",               :type => "string" },
])
